image: atlassian/default-image:2

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  default:
    - step:
        name: Default
        caches:
          - node
        script:
          - cd htcc-admin-tool/
          - npm install
    - step:
        services:
          - docker
        name: Deploy htcc-admin-tool
        deployment: Production
        trigger: manual
        script:
          - cd htcc-admin-tool/
          - docker build -t duyna5/htcc-admin-tool .
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker push duyna5/htcc-admin-tool:latest
          - mkdir -p ~/.ssh
          - cd ../script/
          - cat my_known_hosts >> ~/.ssh/known_hosts
          - (umask  077 ; echo $KEY_DEV_1 | base64 --decode -i > ~/.ssh/id_rsa)
          - ssh root@108.61.162.225 "cd /home/htcc-web/htcc-admin-tool/;./admin.sh"
  custom:
    build-manager-tool:
      - step:
          services:
            - docker
          name: Deploy htcc-manager-tool
          script:
            - cd htcc-manager-tool/
            - docker build -t duyna5/htcc-manager-tool .
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker push duyna5/htcc-manager-tool:latest
            - mkdir -p ~/.ssh
            - cd ../script/
            - cat my_known_hosts >> ~/.ssh/known_hosts
            - (umask  077 ; echo $KEY_DEV_1 | base64 --decode -i > ~/.ssh/id_rsa)
            - ssh root@108.61.162.225 "cd /home/htcc-web/htcc-manager-tool/;./manager.sh"
